services:
  - type: web
    name: grade-report-analyzer
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: HF_TOKEN
        sync: false
