services:
  - type: web
    name: grade-report-ocr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_TOKEN
        sync: false
